//CREATE BLOG ENTRIE
export const CREATE_BLOG_LOADING = "CREATE_BLOG_LOADING";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";


//ALL BLOG ENTRIE
export const ALL_BLOG_LOADING = "ALL_BLOG_LOADING";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_ERROR = "ALL_BLOG_ERROR";
