//CREATE LOGIN
export const CREATE_LOGIN_LOADING = "CREATE_LOGIN_LOADING";
export const CREATE_LOGIN_SUCCESS = "CREATE_LOGIN_SUCCESS";
export const CREATE_LOGIN_ERROR = "CREATE_LOGIN_ERROR";

//AUTHENTICATE LOGIN
export const AUTH_LOGIN_LOADING = "AUTH_LOGIN_LOADING";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

//VERIFY LOGIN
export const VERIFY_LOGIN_LOADING = "VERIFY_LOGIN_LOADING";
export const VERIFY_LOGIN_SUCCESS = "VERIFY_LOGIN_SUCCESS";
export const VERIFY_LOGIN_ERROR = "VERIFY_LOGIN_ERROR";

//LOGOUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
